### ISSUE TITLE
Unable to open the playground in either MacOS desktop or iOS Playgrounds App

### ISSUE THREAD

**Issue by simon-hibbs** [dcutting/GameOfLifeOnMetal#1]
I'm not sure if this is really an issue as I'm not sure if being able to was your intention. I was looking into how to use Metal from  the Playgrounds app, which seems to be an un-solved problem, so that's what brought me to your blog post.

**Comment by dcutting** [comment]
Hi Simon, I believe the Swift Playgrounds app can only run playgrounds written for iOS, even though that app can run on macOS too.

This playground is for macOS so it won't open in that app. If you have a Mac, you should in theory be able to open this playground in Xcode instead. However, I've just tried to open it with Xcode 12.5 and there seem to be some problems so I'll try to fix those when I get a chance.

Sorry none of this really helps you get Metal into the Swift Playgrounds app, but thanks for taking a look anyway!
